# Shell variables
# Generated by 'wal'
# wallpaper='/home/t/dev/rice/wallpaper-qdots'

# Special
background='#0b0a18'
foreground='#dda4a9'
cursor='#dda4a9'

# Colors
color0='#0b0a18'
color1='#5D284F'
color2='#5A475F'
color3='#9B0830'
color4='#E2122E'
color5='#9B2551'
color6='#E0254C'
color7='#dda4a9'
color8='#9a7276'
color9='#5D284F'
color10='#5A475F'
color11='#9B0830'
color12='#E2122E'
color13='#9B2551'
color14='#E0254C'
color15='#dda4a9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
