--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/t/dev/rice/wallpaper-qdots"

-- Special
background="#0b0a18"
foreground="#dda4a9"
cursor="#dda4a9"

-- Colors
color0="#0b0a18"
color1="#5D284F"
color2="#5A475F"
color3="#9B0830"
color4="#E2122E"
color5="#9B2551"
color6="#E0254C"
color7="#dda4a9"
color8="#9a7276"
color9="#5D284F"
color10="#5A475F"
color11="#9B0830"
color12="#E2122E"
color13="#9B2551"
color14="#E0254C"
color15="#dda4a9"
